%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0.4
  minTrackerConfidence: 0.6
  minMatchingScore4Overall: 0.0
  minMatchingScore4SizeSimilarity: 0.5
  minMatchingScore4Iou: 0.2
  minMatchingScore4VisualSimilarity: 0.5
  matchingScoreWeight4VisualSimilarity: 0.6
  matchingScoreWeight4SizeSimilarity: 0.2
  matchingScoreWeight4Iou: 0.2
  minTrackingConfidenceDuringInactive: 0.4
  maxShadowTrackingAge: 30
  probationAge: 3
  earlyTerminationAge: 1
  useUniqueID: 1

TargetManagement:
  enableBboxUnClipping: 1
  maxTargetsPerStream: 150
  minIouDiff4NewTarget: 0.5
  preserveStreamUpdateOrder: 0

TrackState:
  useTrackSmoothing: 1
  trackSmoothingAlpha: 0.5

DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 1

StateEstimator:
  stateEstimatorType: 1
  noiseWeightVar4Loc: 0.05
  noiseWeightVar4Vel: 0.00625

ReID:
  reidType: 1
  batchSize: 100
  workspaceSize: 1000000
  reidFeatureSize: 128
  reidHistorySize: 100

VisualTracker:
  useVisualTracker: 0
